#!/bin/bash
# uruchamiać w głównym katalogu danego repozytorium

find ${PWD} -mindepth 1 -maxdepth 1 -type d ! -iname ".git" | sort > /tmp/srcinfo
while IFS= read -r line || [[ "$line" ]]; do 
	if [[ -e "${line}/PKGBUILD" ]]; then 
		cd "${line}"; makepkg --printsrcinfo > .SRCINFO
		echo "Wygenerowano ${line}/.SRCINFO"
	else
		echo "Nie znaleziono PKGBUILD w ${line}"
	fi
done < /tmp/srcinfo
cd .. && rm /tmp/srcinfo
